-- Creation of Record Table
CREATE TABLE IF NOT EXISTS Record (
    ID INT NOT NULL
    ARTIST_NAME VARCHAR(30) NOT NULL
    SONG_NAME VARCHAR(30) NOT NULL
    LYRICS VARCHAR NOT NULL

    PRIMARY KEY (ID)
)